### PR TITLE
 fix\#79, added code checking conditions in LIC 9 and 11, added inval…

### LINKED ISSUE #79: Implement conditions for all LICs
We need to implement input checks for LICs. David takes LIC1, LIC8, LIC13, see issues #76, #77 and #78, respectively.

### PR DESCRIPTION
**Pull request by KallePettersson**
…id data tests to Lic 9,11,12

### CODE REVIEW

File: src/main/java/group18/LIC/LIC9.java [hunk 1]
```diff
@@ -9,7 +9,7 @@ public static boolean getLic9(double [] xPos, double[] yPos, int numPoints, int
         double angle=-1;
         double lenX;
         double leny;
-        if(numPoints < 5){
+        if(numPoints < 5 || 1 > C_PTS || 1 > D_PTS || (C_PTS + D_PTS) < numPoints -3){
```
Comment (LukasGutenberg) [inline src/main/java/group18/LIC/LIC9.java:12]: C_PTS + D_PTS < numpoints-3 is wrong

**Review by LukasGutenberg — CHANGES_REQUESTED** [review]
see comments

**Review by LukasGutenberg — APPROVED** [review]
LGTM
